server:
  port: 8080
mybatis-plus:
  global-config:
    banner: off
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/spring_test?useSSL=false&allowMultiQueries=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai

